name: Static checks
on:
  pull_request: {}
  push:
    branches:
    - main
jobs:
  go_lint:
    name: Go lint
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container:
      image: golang:1.19
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Go lint
      run: bin/lint --verbose
  go_format:
    name: Go format
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container:
      image: golang:1.19
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Format
      run: bin/fmt
  shellcheck:
    name: shellcheck
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: shellcheck
      # For more information on shellcheck failures:
      # https://github.com/koalaman/shellcheck/wiki/Checks
      run: |
        bin/shellcheck -x -P "./bin" $(grep -rnsle '^#!/usr/bin/env \(bash\|sh\)' ./* | xargs)
  markdown_lint:
    name: Markdown lint
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Markdown lint
      run: bin/markdownlint ./**/*.md --ignore node_modules/
  chart_docs_diff:
    name: Chart readme diff check
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Check docs for diff
      run: bin/helm-docs-diff
